version: '3.8'


services:
  db:
    container_name: parking_space_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: parkingspace_db
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_password
    ports:
      - "2010:5432"
    volumes:
      - parking_db_data:/var/lib/postgresql/data

volumes:
  parking_db_data: